name: serverpod_auth_idp_naver_flutter_example
description: Example NaverSignInService implementation using flutter_naver_login.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  serverpod_auth_idp_naver_flutter:
    path: ../
  flutter_naver_login: ^1.8.0

dev_dependencies:
  flutter_lints: ^4.0.0
