/// Naver identity provider for Serverpod's authentication module.
///
/// This library mirrors the upstream GitHub OAuth2 provider, adapted for
/// Naver Login (NID). It exposes the configuration, business logic, and
/// endpoint required to authenticate users with their Naver accounts.
library;

export 'src/business/naver_idp.dart';
export 'src/business/naver_idp_admin.dart';
export 'src/business/naver_idp_config.dart';
// [NaverAccountDetails] typedef + pure parse helpers.
export 'src/business/naver_profile.dart';
// [NaverAuthSuccess] record + [NaverIdpUtils] helper.
export 'src/business/naver_idp_utils.dart';
export 'src/endpoints/naver_idp_endpoint.dart';
export 'src/exceptions/naver_exceptions.dart';

// Generated by `serverpod generate` — exposes the [NaverAccount] model.
export 'src/generated/protocol.dart';
