/// Kakao identity provider for the Serverpod authentication module
/// (`serverpod_auth_idp`).
///
/// Configure the provider via [KakaoIdpConfig] (or
/// [KakaoIdpConfigFromPasswords]) and expose [KakaoIdpEndpoint] from your
/// server to enable Kakao sign-in.
library;

export 'src/business/kakao_idp.dart';
export 'src/business/kakao_idp_admin.dart';
export 'src/business/kakao_idp_config.dart';
export 'src/business/kakao_profile.dart'
    show KakaoAccountDetails, parseKakaoProfile, parseKakaoTokenResponse;
export 'src/business/kakao_idp_utils.dart' show KakaoAuthSuccess, KakaoIdpUtils;
export 'src/endpoints/kakao_idp_endpoint.dart';
export 'src/exceptions/kakao_exceptions.dart';

// Generated by `serverpod generate` — exposes the module Endpoints dispatcher
// (required so a host server can mount this module) + the [KakaoAccount] model.
export 'src/generated/endpoints.dart';
export 'src/generated/protocol.dart';
